stages:
  train:
    cmd: python Untitled-1.py
    deps:
    - ds

params:
- params.yaml
artifacts:
  model:
    path: model.keras
    type: model
metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step
