name: CML & DVC # name of the workflow
on: [push] # when it will run
permissions:
  contents: write
  pull-requests: write
jobs: # what it will run
  train-and-report: # job name
    runs-on: ubuntu-latest # where it will run  
    steps:
      - uses: actions/checkout@v3 # pre-built step (checkout sourcecode)
      - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'
      - uses: iterative/setup-cml@v1
      - uses: iterative/setup-dvc@v1
      - name: Train model
      env:
        GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
      run: | # custom commands
        echo "Train model"
        dvc pull 
        dvc repro